version: '3.9'
services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000

  admin_db:
    container_name: django_admin_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306